### ISSUE TITLE
子组件生成加入 rid 后，再次更新后，容器内 dom 结构发生变化。

### ISSUE THREAD

**Issue by vlin** [Qfang-FrontEnd/coala#4]
![snip20150919_1](https://cloud.githubusercontent.com/assets/239585/9965130/c45fceac-5e66-11e5-83db-b34663e933ee.png)
子组件内数据变化触发的更新与第一次更新的 dom 结点不同。

**Comment by cheft** [comment]
第一次为子组件加了个 rid 然后 append 到 repositories 下，这个时候是正确的。第二次更新时  rid 下的 dom 清空再渲染出 带父div的dom ，这时候就多个 div 了，考虑下怎么改进。
